# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
     - cron:  '*/5 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Today's feed
    - uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: python -m pip install requests,
        python -m pip install bs4,
        python main.py
        echo Add other actions to build,
        echo test, and deploy your project.
